### ISSUE TITLE
Can't enable motion from flow

### ISSUE THREAD

**Issue by Puntoboy** [andesse/hue-clip-api.node-red-flows#15]
**Describe the bug**
I have a flow that disables the motion sensor for 10 minutes, then enables it again. I'm migrating from Hue Magic. When I run the flow, the motion disables but after the timeout, it doesn't come back on. 

**To Reproduce**

`[{"id":"c13967da.3c8eb","type":"api-call-service","z":"95e7528c.dd36c","name":"Hallway Lights On","server":"7741cb1d.3b20c4","version":5,"debugenabled":false,"domain":"light","service":"turn_on","areaId":[],"deviceId":[],"entityId":["light.hallway_lamp_1_2","light.hallway_lamp_2_2"],"data":"{\"brightness_pct\":\"100\"}","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","output_location":"","output_location_type":"none","x":610,"y":2160,"wires":[[]]},{"id":"56c13fe5.bdb578","type":"server-events","z":"95e7528c.dd36c","name":"","server":"7741cb1d.3b20c4","version":1,"event_type":"call_service","exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"waitForRunning":true,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"eventData"},{"property":"topic","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"},{"property":"event_type","propertyType":"msg","value":"$outputData(\"eventData\").event_type","valueType":"jsonata"}],"x":110,"y":2260,"wires":[["c161c505.f81688","1ea28cc1.795d83","cf5cb79e.773fe"]]},{"id":"c161c505.f81688","type":"switch","z":"95e7528c.dd36c","name":"Cat Litter Time","property":"payload.event.service_data.entity_id","propertyType":"msg","rules":[{"t":"eq","v":"script.cat_litter_time","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":320,"y":2240,"wires":[["c13967da.3c8eb"]]},{"id":"1ea28cc1.795d83","type":"debug","z":"95e7528c.dd36c","name":"cat","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":330,"y":2400,"wires":[]},{"id":"cf5cb79e.773fe","type":"switch","z":"95e7528c.dd36c","name":"Cat Litter Time","property":"payload.event.service","propertyType":"msg","rules":[{"t":"eq","v":"cat_litter_time","vt":"str"}],"checkall":"true","repair":false,"outputs":1,"x":320,"y":2280,"wires":[["c13967da.3c8eb","8a25c2702f5bc1bf","fbe2cfcb2f23f0ce"]]},{"id":"31f859355b193fa6","type":"inject","z":"95e7528c.dd36c","name":"","props":[{"p":"payload.event.service","v":"cat_litter_time","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":90,"y":2340,"wires":[["cf5cb79e.773fe"]]},{"id":"8a25c2702f5bc1bf","type":"trigger","z":"95e7528c.dd36c","name":"","op1":"","op2":"","op1type":"nul","op2type":"date","duration":"10","extend":true,"overrideDelay":false,"units":"s","reset":"STOP","bytopic":"all","topic":"topic","outputs":1,"x":590,"y":2220,"wires":[["6e02db78.1ba654","b4fc6368397392df","662c1aa1b617feae"]]},{"id":"662c1aa1b617feae","type":"debug","z":"95e7528c.dd36c","name":"cat","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":950,"y":2280,"wires":[]},{"id":"6e02db78.1ba654","type":"api-call-service","z":"95e7528c.dd36c","name":"Hallways Lights Off","server":"7741cb1d.3b20c4","version":5,"debugenabled":false,"domain":"light","service":"turn_off","areaId":[],"deviceId":[],"entityId":["light.hallway_lamp_1_2","light.hallway_lamp_2_2"],"data":"","dataType":"json","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","output_location":"","output_location_type":"none","x":910,"y":2160,"wires":[[]]},{"id":"b144094da62d3035","type":"inject","z":"95e7528c.dd36c","name":"","props":[{"p":"payload.event.service","v":"cat_litter_time","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":710,"y":2360,"wires":[["6e02db78.1ba654"]]},{"id":"fbe2cfcb2f23f0ce","type":"link out","z":"95e7528c.dd36c","name":"link out 1","mode":"link","links":["c3e862fe.aaf66"],"x":645,"y":2280,"wires":[]},{"id":"b4fc6368397392df","type":"link out","z":"95e7528c.dd36c","name":"link out 2","mode":"link","links":["b1aa549b.424a38"],"x":835,"y":2220,"wires":[]},{"id":"7741cb1d.3b20c4","type":"server","name":"Home Assistant","version":4,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m"}]`

**Expected behavior**
I expect the motion sensor to be enabled

**Comment by andesse** [comment]
Hey,

what is this? You are using nodes that are not part of my flow example.

Use my example,  deactivate the sensor, use a delay node for the time you need and activate it again. 
There is a description in the labels of my flow how sensor enable and disable api calls work. 

I can’t help with your setup. 

![IMG_2514](https://user-images.githubusercontent.com/76150626/183686847-262f6b31-f8f8-486c-8322-814a7ac14daa.jpeg)

**Comment by Puntoboy** [comment]
There are two lights which aren't in Hue, I use Home Assistant. 

![image](https://user-images.githubusercontent.com/11718878/183687301-4c05a9af-ce56-4bb8-982f-825a078cd3cb.png)

**Comment by andesse** [comment]
Is your wish that the lower cat litter time disable - and the top one enable the sensor

**Comment by andesse** [comment]
And http request for sensors looks like that:
![IMG_2516](https://user-images.githubusercontent.com/76150626/183688544-ac3b4cf1-ade1-472a-bbb0-826c22601ea6.jpeg)
![IMG_2517](https://user-images.githubusercontent.com/76150626/183688595-8024ea40-f91d-49ce-ad05-f0e217fc5209.jpeg)
 
 one change node contains the data for enabling it, the other one for disable it. 
 both go into the header and the http request. You need to add your discovered data in all nodes. Otherwise it won’t work.

**Comment by Puntoboy** [comment]
If I manually click the timestamp nodes here, the sensor enables and disables as I expect. IT seems to be and issue with the links between my flow and your flow. I've probably done something wrong.

![image](https://user-images.githubusercontent.com/11718878/183689276-7d2f8b7d-bcba-4bfe-8f70-3fc7efeae16e.png)

**Comment by andesse** [comment]
When it works with the inject nodes everything is fine. You probably linked it not correct. 
i am closing the issue then.

**Comment by Puntoboy** [comment]
Enabled

![image](https://user-images.githubusercontent.com/11718878/183689646-34aab8ef-b7dd-42e6-97ae-881c13961e2c.png)

Disabled

![image](https://user-images.githubusercontent.com/11718878/183689720-a0f15ea2-0856-411f-8dc8-ef81c6cd6412.png)

**Comment by andesse** [comment]
@Puntoboy check if your link out are correctly connected to the link in nodes. 
Gives them a name as recommended in the readme. Otherwise it’s too confusing

**Comment by Puntoboy** [comment]
The link node is named.

![image](https://user-images.githubusercontent.com/11718878/183693971-51b373c4-06f0-4bb9-859e-3b697b82afe6.png)

**Comment by andesse** [comment]
Where comes this timeout from?
You can’t make too much api calls at once. Please read the readme. You are the first with this problem. It seems to be in your flow. 

Debug everything and try to find the error

**Comment by Puntoboy** [comment]
As I test, I'm linking directly HTTP request. Same issue. This is my only API call at the moment as I'm just setting it up.

![image](https://user-images.githubusercontent.com/11718878/183700840-edda3006-f3cb-4418-b4fc-0f842769fd42.png)


![image](https://user-images.githubusercontent.com/11718878/183700891-b9e83829-ddf2-495d-9411-a52bb7b4146b.png)

**Comment by Puntoboy** [comment]
> As I test, I'm linking directly HTTP request. Same issue. This is my only API call at the moment as I'm just setting it up.
> 
> ![image](https://user-images.githubusercontent.com/11718878/183700840-edda3006-f3cb-4418-b4fc-0f842769fd42.png)
> 
> ![image](https://user-images.githubusercontent.com/11718878/183700891-b9e83829-ddf2-495d-9411-a52bb7b4146b.png)

I'm not saying it's a bug with this setup, I've likely done something wrong, but I can't see what it is.

**Comment by andesse** [comment]
I can see it now. Use a 10 second delay node instead of the trigger node.

**Comment by Puntoboy** [comment]
Still seeing the JSON parse error.

![image](https://user-images.githubusercontent.com/11718878/183702348-fec72abd-04fd-47a7-8f2e-9dece8374d08.png)

Neither the disable or enable are working consistently.

**Comment by andesse** [comment]
Ok, debug the data before it reaches the change nodes. You probably need to delete all extra data that comes from your home assistant node. I am pretty sure now that it mess up the payload. 

You can try it. Remove the home assistant node, and inject a Boolean true there at the position. If it works you msg is messed up by that node

**Comment by andesse** [comment]
@Puntoboy what is events call service?

**Comment by Puntoboy** [comment]
That listened to events from Home Assistant. The switch node after it, filters for a specific event, in this case when a specific script is run in HA.

**Comment by andesse** [comment]
@Puntoboy ok… what event. Specific, maybe we find a workaround

**Comment by Puntoboy** [comment]
![image](https://user-images.githubusercontent.com/11718878/183707164-9f1682bb-fb42-477d-948b-b827f164e835.png)

**Comment by andesse** [comment]
@Puntoboy no, the home assistant node. What is the script for? 
please debug (full msg object) what comes out of the home assistant node
