### ISSUE TITLE
Sample for new 4.3 converter with SSE_Event_Stream

### ISSUE THREAD

**Issue by unclej84** [andesse/hue-clip-api.node-red-flows#26]
I did not use the events node but the SSE_Event_Stream. How to merge the new converter subflow to this flow? Maybe you could add an additional image or a short description? Or would this be working already?

**Comment by andesse** [comment]
Hey @unclej84 you can see it on the screenshot, you just add it in between the output of the SSE Events (or the Hue Events node from yadomi) and the link out node that is connected to the receivers. When you import the flow it should be easy to understand, cause I connected the link nodes already there.
