### ISSUE TITLE
Comments / Suggestions

### ISSUE THREAD

**Issue by marc-gist** [andesse/hue-clip-api.node-red-flows#3]
Thanks for this! Very well laid out and commented.

A suggestion for your "HUE API V2" function, changing to this can make setup for a new user faster:
```

// you can copy the user key from the hue config node out of Huemagic
var user = "YOUR CODE";
var ip = "YOUR IP"

if(msg.endpoint === undefined)
 msg.url = "https://" + ip + "/clip/v2/resource";
else if(msg.topic === undefined)
 msg.url = "https://" + ip + "/clip/v2/resource/" + msg.endpoint;
else
 msg.url = "https://" + ip + "/clip/v2/resource/" + msg.endpoint + "/" + msg.topic;

```

It would also be great to have an example flow to get the current state of a group/light like:
```
[{"id":"b74f58013a96f441","type":"change","z":"ad06319bce270ec2","name":"Get State","rules":[{"t":"set","p":"endpoint","pt":"msg","to":"grouped_light","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"GROUP RID","tot":"str"},{"t":"set","p":"payload","pt":"msg","to":"{}","tot":"json"},{"t":"set","p":"verb","pt":"msg","to":"get","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":600,"y":400,"wires":[[]]}]
```

![image](https://user-images.githubusercontent.com/4084427/174445121-ff8fce9b-3ece-42fd-b381-3571e660ce31.png)

Would also need to add how to grab that data filtering by the RID on the response side. but hopefully most can figure that out if they got this far :)

**Comment by andesse** [comment]
@marc-gist thanks for the suggestion, I added the two nodes to the repository. 
Thanks for the thing with the RID, the description in the Room change node was not correct. The RID need to be added, the text said ID. I changed that.
