### ISSUE TITLE
cannot read rid for zones

### ISSUE THREAD

**Issue by Schmetterfliege** [andesse/HUE-CLIP-API.Node-RED-Flows#38]
**Describe the bug**
Created a new zone and scene in hue app and wanted to add some automation, but it doesn't load any zones at all and therefore no scenes for zones...
Manually triggering the "get Zones" shows my zones. But manually triggering "Scenes (zones)" shows an empty array because the zones are not stored in the data.

**To Reproduce**
Trigger "Request all Data"

**Expected behavior**
Zones should show

**Screenshots**
![image](https://user-images.githubusercontent.com/76066402/212438198-abd14d34-b0a1-4488-8f34-d200fc4314e2.png)

I know it worked in the past, because I do have an automation for another scene in another zone. But that was many weeks ago.
Not sure what could have changed...
Tried it with the flow that was the current one a few months ago, and now with the latest flow. Exact same issue :(
I imported the latest flow, connected my bridge again successfully etc. But this part still fails.
I didn't change anything in the function nodes.

**Comment by Schmetterfliege** [comment]
![image](https://user-images.githubusercontent.com/76066402/212439036-a1b492e6-181f-4bf0-95f1-1ee86c011070.png)

Flow context doesn't have "zones", only the "zones_array". No idea why, the node "Zone Name and ID" works, it sends the correct data to the debug node behind it, but for some reason the "zones" change node that sets the flow context doesn't do anything. However, I don't see an issue with that node

**Comment by andesse** [comment]
Hey,

for me it works, on two bridges, one normal - the other one in beta program.
I don’t get the rid in the array as well, I actually believe that never use this function still.
All data shows up when I read the zones separately. 

Did you try to restart node red?
If it’s not working, please get a new API Token and try.
Otherwise restart the HUE Bridge, when you never changed something it should work.

The nodes running with zero Issues since my last release.

Grüße
Andreas

![IMG_4350](https://user-images.githubusercontent.com/76150626/212439924-8077d115-5698-41a6-83c0-05c69c140cbe.jpeg)

**Comment by andesse** [comment]
@Schmetterfliege if you created a group, that might be depreciated by HUE in the Firmware. Rooms and Zones should work

**Comment by Schmetterfliege** [comment]
![image](https://user-images.githubusercontent.com/76066402/212440770-bce2ce78-5003-43bf-8265-42ab4338a901.png)

**Comment by Schmetterfliege** [comment]
when triggering "Get all data" it is sending something to the "Zone Name and ID" function node, but the data is missing the RIDs in the "services" field. But why?
When I trigger get zones_array, they do show the RIDs:
![image](https://user-images.githubusercontent.com/76066402/212440865-56396d92-904e-4f77-a630-3010ac17d5ea.png)

**Comment by Schmetterfliege** [comment]
In other words:
![image](https://user-images.githubusercontent.com/76066402/212441021-214f9cbd-6bf6-42c3-9140-377481bc48cc.png)
This is able to read the RIDs from the bridge.
But "Get all data" is *not* able to read the RIDs (I assume?)

**Comment by Schmetterfliege** [comment]
@andesse 
should have read your comment thoroughly. So error in my initial report is expected?

**Comment by Schmetterfliege** [comment]
@andesse 
Mein Problem sind prinzipiell nicht die Zonen - die sind ja als Array im Flow gespeichert.
Mein Problem ist dass ich die Szenen der Zonen nicht bekomme, weil die zugehörige Node dafür im Flow "zones" benutzt.
Aber das existiert ja nicht im Flow, sondern nur "zones_array".

**Comment by andesse** [comment]
@Schmetterfliege i have zones in my zone array, this gets split up when you read all data separately. Or you can Access the array there directly. I use the same function node like you.

Please try all recommend steps:)
I go to bed now, I’ll have a look tomorrow morning for your reply. 

![IMG_4354](https://user-images.githubusercontent.com/76150626/212441770-9ff18990-3be6-4b56-96c6-d544f59ef83e.jpeg)
![IMG_4353](https://user-images.githubusercontent.com/76150626/212441802-7c05b995-6fd3-4dcd-9aec-e33e63372cdc.jpeg)

**Comment by Schmetterfliege** [comment]
Hast du denn "zones" in deinen Flow Variablen?

**Comment by andesse** [comment]
> Hast du denn "zones" in deinen Flow Variablen?

@Schmetterfliege natürlich. Aus Versehen gelöscht?
![image](https://user-images.githubusercontent.com/76150626/212443014-8eba3ef7-3bf0-4607-adc7-5a55bd19fc71.jpeg)

**Comment by Schmetterfliege** [comment]
Nein, habe aber das Problem gefunden:
![image](https://user-images.githubusercontent.com/76066402/212443113-e11068e3-ae8e-4f65-89d1-2a07dfa58c60.png)

Ich habe 5 Zonen, 2 davon haben keine Lampen und deshalb keine RID eingetragen.
Die function Node die die Zonen setzt geht das Array durch, der erste Eintrag ist so eine Zone die keine Lampe hat -> keine RID -> Function Node geht in einen Error statt diese beiden Zonen zu überspringen.

Wäre vielleicht eine Verbesserung, da noch einzubauen dass wenn keine RID existiert (weil Zone keine Geräte hat) dass er dann keinen Error wirft, sondern verwirft und zum nächsten item im Array geht :)

**Comment by Schmetterfliege** [comment]
Habe die beiden Zonen die keine Geräte haben gelöscht - nun läufts problemlos :)

**Comment by andesse** [comment]
@FredBlo when a Zone has no lamp it returns an error on request. 

Can you edit the function node, so that Zone and rooms that has no devices inside, get ignored and reads the data from the next instead of returning an error?
