### ISSUE TITLE
SSE_Event_Stream setup problem

### ISSUE THREAD

**Issue by patrickharris** [andesse/HUE-CLIP-API.Node-RED-Flows#41]
I have just started using your SSE event stream experimentally, as Yadomi's event node seems to lose connection every month or so.

It seems with @tq-bit/node-red-contrib-server-sent-events v1.2.6 the SSE client node has perhaps changed the way it works. I'm using it for the first time, and wasn't able to get your inject nodes hooked up to it. Also it took me a while to get it working - I had to use an event of "message" and a header with my hue key, `{"hue-application-key":"1234567"}`. Either I might be misunderstanding the setup, or perhaps you could update the SSE_Event_Stream?

Thanks very much for your work by the way - your library here has been invaluable to me over the last few years.

**Comment by andesse** [comment]
@patrickharris 

You need the

node-red-contrib-sse-client (0.2.4)

Then it should work.

**Comment by patrickharris** [comment]
Argh, my bad. Thanks very much for that Andreas. :)
