### ISSUE TITLE
using environment variables for the api config

### ISSUE THREAD

**Issue by msmthng** [andesse/hue-clip-api.node-red-flows#9]
it would be easier to setup the api v2 nodes if you use env vars instead of editing data in each node:

var user = env.get('hue-application-key');

if(msg.endpoint === undefined)
 msg.url = "https://"+env.get('hue-bridge-ip')+"/clip/v2/resource";
else if(msg.topic === undefined)
 msg.url = "https:/"+env.get('hue-bridge-ip')+"/clip/v2/resource/" + msg.endpoint;
else
 msg.url = "https://"+env.get('hue-bridge-ip')+"/clip/v2/resource/" + msg.endpoint + "/" + msg.topic;

**Comment by andesse** [comment]
@msmthng please share a small sample flow. I’ll check It out. Not sure what information I need to enter there.

**Comment by andesse** [comment]
@msmthng ok, got it working, won’t use it for my flow. 
That’s the request to get all data from the bridge. I make it separate on the helper flow, so you can just get scenes / lights / devices in groups. Not so much effort to search for data. The data is also stored in context (default) so you have access for it. Having this huge array waste too much time with searching. Try my system. 
inject „scenes separately“ than you get a nice json feedback with name, Id, rid , device. Very easy

**Comment by andesse** [comment]
@msmthng read inside the white labels

**Comment by andesse** [comment]
@msmthng my Flow Outputs scenes like this. You don’t need to unfold the huge array
![IMG_2434](https://user-images.githubusercontent.com/76150626/180973548-42064f0f-77ef-44df-853e-ec9385076527.jpeg)

**Comment by msmthng** [comment]
do you know how i can set the color for a grouped_light and query for that?

**Comment by andesse** [comment]
@msmthng its the same like setting it for a light, just change the endpoint to grouped_light. 

the easiest way to get the exact color you desire is to set it in the hue app, and watch the event flow. 
the last message published by the bridge, contains the color code (it is the last one, cause in between the bridge will send the colors from the transition)

**Comment by msmthng** [comment]
@andesse do you know how exactly the dynamics on changing the brightness is working:

{“dynamics”:{“duration”:1000},“dimming_delta”:{“action”:“up”,“brightness_delta”:10}}

this changes exaclty one time with 10, if i change to 100 it changes faster then set in duration to full light.

i would expect that i can start a transition with a given time and stop it with action stop before the end of transition is reached but this doesn't realy work.

thx

**Comment by andesse** [comment]
@msmthng Good Morning :)
https://github.com/andesse/hue-clip-api.node-red-flows/blob/main/Change%20Node%20Examples.json
In my Flow are sample nodes where the time / brightness just need to be adjusted. 

But I setup 2 Nodes just 10 Minutes ago if I can reproduce this. 
One node has 10% brightness and 3000ms dynamics (N1)
Second node has 100% brightness and 1000ms dynamics (N2)

I setup my flow that 500ms after N1 got injected the N2 gets injected. It directly changed after 500ms from dimming down to N2 state. So the command got „overwritten“

I hope this helps. 
i am not allowed to share the Developer Documentation, but I am allowed to tell you where to access it:
https://developers.meethue.com/

I recommend to make an account. They ask for nothing. They are happy with everyone who is using their API, cause that means they sell more lights :)

**Comment by andesse** [comment]
@msmthng
![IMG_2477](https://user-images.githubusercontent.com/76150626/181461966-6b9ee95d-bd30-428c-a1a1-c3a75e75d175.jpeg)

**Comment by msmthng** [comment]
I have an account i was using the api reference, since i didn't got an answer on my question in der forum i pointed my questio to you as well. since i have recognized that you are very fast in answering. thx

**Comment by andesse** [comment]
@msmthng when keeping all small issues at the side, that you will resolve very quick…

Ary you happy with this kind of setup? Being independent. 


Yadomi just made small changes recently, to avoid disconnecting from the bride. It appears when for a longer timespan no events are posted. I never had a problem cause I have lots of sensors sending data frequently. 
so this setup should be completely struggle free now.

**Comment by msmthng** [comment]
the second example in your link (Dimming 10% down / 1s transition) is dimming down ones by 10% once - is there a way to initiate a dimming down process with 10% per second?

**Comment by msmthng** [comment]
overall iam happy with this setup. struggeling a little bit with dynamic stransitions ( for dimming down and up). in past i have implemented this with the delay node and using some flow vars. looking at the api i thought i can exchange that with this dynamics in the api during the refactoring process to make this more simple

**Comment by msmthng** [comment]
you don't have any issues with duration? for me it doesn't get slower if i set 2000 or 4000 ms.

**Comment by andesse** [comment]
@msmthng you need to calculate your dimming time. 
10% per second? For how long?

example: light is at 100% you want to dim it down to 20% in 10% steps
100-20 is 80 = 8000ms dynamics duration and dimming value would be 10

then it would take 8 seconds in 10% steps to go from 100 to 20
Is that what you mean? :)

**Comment by andesse** [comment]
> you don't have any issues with duration? for me it doesn't get slower if i set 2000 or 4000 ms.

@msmthng this works completely fin
![IMG_2478](https://user-images.githubusercontent.com/76150626/181475046-6fbf8a78-484f-4a59-a0bc-146b22c226e2.jpeg)
e

**Comment by msmthng** [comment]
![image](https://user-images.githubusercontent.com/40269445/181486273-5da60107-584c-4f6f-8b2b-1be49a2446e7.png)

![image](https://user-images.githubusercontent.com/40269445/181486391-a2cbffe4-a432-4694-91ff-eb9c6400a1a2.png)


![image](https://user-images.githubusercontent.com/40269445/181487102-69bfc05c-3bea-4230-b707-8515e43fd422.png)

no idea why

**Comment by andesse** [comment]
@msmthng dont get it 32 to 15 are 17 seconds. 
why is your time not in sync? 
You inject at 12:xx:xx ish and get a creation time with 10:xx:xx back. How come?

Check the time servers for bridge and NodeRed system, or if NR is in a container, the main system running it. 
Maybe that’s the problem. API says durations of 21600000ms work. I tried some with 60000ms and it worked. 

Are you using not original brand hue Controlers/lamps?

**Comment by andesse** [comment]
@msmthng wait… you send this to a group? That might not work. Check the api documentation. For a group they just vaguely say „time for….“ the high times just count for lights and not grouped_lights endpoints.

i think that’s your problem. How many lights are in this group? Trigger them as lights one after the other with 500ms delay for the command injection to achieve a group effect

**Comment by msmthng** [comment]
![image](https://user-images.githubusercontent.com/40269445/181499485-316e65ac-4bcd-4b7a-ac8a-9bee29b8013d.png)
the same using a ight - the "effect" is done by the bulb or the bridge?

**Comment by andesse** [comment]
@msmthng ok, my time is off as well by two hours. Then that’s not the problem. 
in my understanding it is like this. 
- you send the parameters via https to the bridge
- The Bridge sends these parameters to the device via Zigbee
- The device itself runs the effect by itself. That’s the reason that another parameter send from the bridge overwrites it. 
- in between the lamp / device sends all changes via Zigbee to the bridge and the bridge returns this changes in the eventstream that we are listening too.

**Comment by andesse** [comment]
@msmthng can you explain what effect you want to achieve?
Maybe you need to use the sunset effect

**Comment by msmthng** [comment]
![image](https://user-images.githubusercontent.com/40269445/181716384-f8f25800-bb1d-4875-bd1a-7ceb23f3e576.png)
maybe it is an issue of ikea bulbs and dimming i had to do it this way.
trigger dimming up and down triggered by some conditions.

**Comment by andesse** [comment]
@msmthng thats what I asked earlier „ Are you using not original brand hue Controlers/lamps?“ 

only original HUE lamps offer the full features. That’s the reason HUE is more expensive.

**Comment by msmthng** [comment]
@andesse sorry didn't see that question. but now my setup is much more stable. I think it is really much more straight forward to use the rest API directly.

**Comment by andesse** [comment]
> @msmthng dont get it 32 to 15 are 17 seconds. why is your time not in sync? You inject at 12:xx:xx ish and get a creation time with 10:xx:xx back. How come?
> 
> Check the time servers for bridge and NodeRed system, or if NR is in a container, the main system running it. Maybe that’s the problem. API says durations of 21600000ms work. I tried some with 60000ms and it worked.
> 
> Are you using not original brand hue Controlers/lamps?
> 
> not easy to debug your problem hahah

@msmthng here

**Comment by andesse** [comment]
@msmthng 
I close the issue
